import { useCallback, useEffect, useMemo, useState } from 'react'
import { Download, FileUp, MessageCircle, Save } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
import { useAuth } from '../../context/AuthContext'
import { Badge, Button, EmptyState, FullPageSpinner, Input, PageHeader, SectionCard, Select, StatCard, Table, Td, Textarea, Tr } from '../../components/ui'

const managers = ['admin_yayasan', 'admin_unit', 'kepala_sekolah', 'wakil_kepala_sekolah']
const today = new Date().toISOString().slice(0, 10)
const statusName = { aktif: 'Aktif', pindah: 'Pindah', lulus: 'Lulus', nonaktif: 'Nonaktif', pelanggaran: 'Pelanggaran', pembinaan_bk: 'Pembinaan BK', prestasi: 'Prestasi', draft: 'Draf', siap_dikirim: 'Siap dikirim', terkirim: 'Terkirim' }
const tone = (value) => (['aktif', 'prestasi', 'terkirim'].includes(value) ? 'success' : ['pelanggaran', 'nonaktif'].includes(value) ? 'danger' : 'gold')

function useStudentScope() {
  const { profile } = useAuth()
  const canManage = managers.includes(profile?.role)
  const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const [students, setStudents] = useState([]); const [units, setUnits] = useState([]); const [classes, setClasses] = useState([])
  const load = useCallback(async () => {
    setLoading(true); setError('')
    const [{ data: s, error: se }, { data: u, error: ue }, { data: c, error: ce }] = await Promise.all([
      supabase.from('students').select('id,nis,nisn,full_name,current_unit_id,status,guardians(id,full_name,phone,email,is_primary_contact)').order('full_name'),
      supabase.from('units').select('id,code,name').order('code'),
      supabase.from('classes').select('id,name,unit_id,academic_year_id').order('name'),
    ])
    setStudents(s || []); setUnits(u || []); setClasses(c || []); setError(se?.message || ue?.message || ce?.message || ''); setLoading(false)
  }, [])
  useEffect(() => { load() }, [load])
  return { profile, canManage, loading, error, setError, students, units, classes, load }
}

const csvTemplate = 'nis,nisn,nama,jenis_kelamin,kode_unit,kelas,nama_wali,no_hp_wali,email_wali\n2026001,0012345678,Contoh Siswa,L,SD,VI-A,Contoh Wali,081234567890,wali@example.com\n'
const csvRows = (text) => {
  const lines = text.replace(/^\uFEFF/, '').trim().split(/\r?\n/).filter(Boolean)
  if (lines.length < 2) return []
  const parse = (line) => { const output = []; let value = ''; let quote = false; for (let i = 0; i < line.length; i += 1) { const ch = line[i]; if (ch === '"') { if (quote && line[i + 1] === '"') { value += '"'; i += 1 } else quote = !quote } else if (ch === ',' && !quote) { output.push(value.trim()); value = '' } else value += ch } output.push(value.trim()); return output }
  const headers = parse(lines[0]).map((v) => v.toLowerCase().trim())
  return lines.slice(1).map((line, index) => Object.fromEntries(headers.map((key, i) => [key, parse(line)[i] || '']).concat([['_row', index + 2]])))
}

export function StudentImportPage() {
  const { profile, canManage, loading, error, setError, students, units, classes, load } = useStudentScope()
  const [rows, setRows] = useState([]); const [fileName, setFileName] = useState(''); const [unitId, setUnitId] = useState(''); const [saving, setSaving] = useState(false); const [result, setResult] = useState(null)
  const download = () => { const url = URL.createObjectURL(new Blob([csvTemplate], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'template-impor-siswa.csv'; link.click(); URL.revokeObjectURL(url) }
  const read = async (event) => { const file = event.target.files?.[0]; if (!file) return; if (!file.name.toLowerCase().endsWith('.csv')) { setError('Gunakan berkas CSV. Template ini dapat dibuka dan disimpan kembali melalui Microsoft Excel.'); return } const parsed = csvRows(await file.text()); setFileName(file.name); setRows(parsed); setResult(null); if (!parsed.length) setError('Berkas tidak berisi baris data yang dapat diimpor.') }
  const importRows = async () => {
    if (!canManage || !rows.length || !unitId) return
    setSaving(true); setError(''); let accepted = 0; let rejected = 0; const unitByCode = Object.fromEntries(units.map((u) => [u.code.toLowerCase(), u])); const classByUnitName = Object.fromEntries(classes.map((c) => [`${c.unit_id}:${c.name.toLowerCase()}`, c])); const knownNis = new Set(students.map((s) => s.nis))
    for (const row of rows) {
      const unit = row.kode_unit ? unitByCode[row.kode_unit.toLowerCase()] : units.find((u) => u.id === unitId)
      if (!row.nis || !row.nama || !unit || knownNis.has(row.nis)) { rejected += 1; continue }
      const { data: student, error: studentError } = await supabase.from('students').insert({ nis: row.nis, nisn: row.nisn || null, full_name: row.nama, gender: row.jenis_kelamin || null, current_unit_id: unit.id, status: 'aktif' }).select('id').single()
      if (studentError || !student) { rejected += 1; continue }
      knownNis.add(row.nis); accepted += 1
      const steps = []
      if (row.nama_wali) steps.push(supabase.from('guardians').insert({ student_id: student.id, full_name: row.nama_wali, phone: row.no_hp_wali || null, email: row.email_wali || null, relation: 'wali', is_primary_contact: true }))
      const targetClass = row.kelas && classByUnitName[`${unit.id}:${row.kelas.toLowerCase()}`]
      if (targetClass) steps.push(supabase.from('class_enrollments').insert({ student_id: student.id, class_id: targetClass.id }))
      await Promise.all(steps)
    }
    await supabase.from('student_import_batches').insert({ unit_id: unitId, file_name: fileName || 'impor-manual.csv', total_rows: rows.length, accepted_rows: accepted, rejected_rows: rejected, notes: 'Impor data siswa melalui Kesiswaan', created_by: profile.id })
    setSaving(false); setResult({ accepted, rejected }); load()
  }
  if (loading) return <FullPageSpinner />
  return <div><PageHeader title="Impor & kualitas data" description="Masukkan data siswa dan wali secara massal dengan template yang konsisten." actions={<Button variant="outline" onClick={download}><Download className="h-4 w-4" />Unduh template</Button>} />{error && <p className="mb-4 text-sm text-[var(--color-danger)]">{error}</p>}<div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><SectionCard title="Impor CSV dari Excel" description="Simpan lembar Excel sebagai CSV UTF-8, lalu unggah di sini.">{canManage ? <div className="grid gap-4"><Select label="Unit tujuan" value={unitId} onChange={(e) => setUnitId(e.target.value)}><option value="">Pilih unit</option>{units.map((u) => <option key={u.id} value={u.id}>{u.code} · {u.name}</option>)}</Select><Input label="Berkas CSV" type="file" accept=".csv,text/csv" onChange={read} /><p className="text-xs text-[var(--color-ink-soft)]">Kolom wajib: nis, nama. Kolom lain pada template akan melengkapi profil wali dan kelas.</p><Button disabled={!rows.length || !unitId || saving} onClick={importRows}><FileUp className="h-4 w-4" />{saving ? 'Mengimpor…' : `Impor ${rows.length} baris`}</Button>{result && <p className="text-sm text-[var(--color-success)]">Selesai: {result.accepted} diterima, {result.rejected} ditolak (duplikat atau data wajib belum lengkap).</p>}</div> : <p className="text-sm text-[var(--color-ink-soft)]">Hanya pimpinan unit dapat mengimpor data siswa.</p>}</SectionCard><SectionCard title="Pratinjau data" description={rows.length ? `${rows.length} baris siap diperiksa` : 'Unggah berkas untuk melihat data sebelum diimpor.'}>{rows.length ? <Table columns={['Baris','NIS','Nama','Unit','Kelas','Wali']} >{rows.slice(0, 10).map((r) => <Tr key={r._row}><Td>{r._row}</Td><Td>{r.nis}</Td><Td>{r.nama}</Td><Td>{r.kode_unit || 'Unit pilihan'}</Td><Td>{r.kelas || '—'}</Td><Td>{r.nama_wali || '—'}</Td></Tr>)}</Table> : <EmptyState title="Belum ada pratinjau" description="Gunakan template agar struktur data terbaca dengan benar." />}</SectionCard></div></div>
}

export function StudentTransitionPage() {
  const { canManage, loading, error, setError, students, classes, load } = useStudentScope(); const [studentId, setStudentId] = useState(''); const [status, setStatus] = useState('pindah'); const [note, setNote] = useState(''); const [fromClass, setFromClass] = useState(''); const [toClass, setToClass] = useState(''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  const updateStatus = async (e) => { e.preventDefault(); if (!studentId) return; setSaving(true); const { error: one } = await supabase.from('students').update({ status }).eq('id', studentId); const { error: two } = await supabase.from('student_status_history').insert({ student_id: studentId, status, note: note || null }); setSaving(false); if (one || two) setError((one || two).message); else { setMessage('Status dan riwayat siswa tersimpan.'); setNote(''); load() } }
  const promote = async (e) => { e.preventDefault(); if (!fromClass || !toClass || fromClass === toClass) return; setSaving(true); const { data: active, error: readError } = await supabase.from('class_enrollments').select('id,student_id').eq('class_id', fromClass).is('ended_at', null); if (readError) { setError(readError.message); setSaving(false); return }; const now = new Date().toISOString(); const results = await Promise.all((active || []).flatMap((row) => [supabase.from('class_enrollments').update({ ended_at: now }).eq('id', row.id), supabase.from('class_enrollments').insert({ student_id: row.student_id, class_id: toClass })])); const failed = results.find((r) => r.error); setSaving(false); if (failed?.error) setError(failed.error.message); else { setMessage(`${active?.length || 0} siswa dipindahkan dengan riwayat kelas tetap tersimpan.`); load() } }
  if (loading) return <FullPageSpinner />
  return <div><PageHeader title="Mutasi, kenaikan & kelulusan" description="Ubah status siswa dengan jejak riwayat yang tetap dapat diaudit." />{(error || message) && <p className={`mb-4 text-sm ${error ? 'text-[var(--color-danger)]' : 'text-[var(--color-success)]'}`}>{error || message}</p>}<div className="grid gap-6 lg:grid-cols-2"><SectionCard title="Status individual" description="Untuk mutasi, kelulusan, atau penonaktifan.">{canManage ? <form onSubmit={updateStatus} className="grid gap-4"><StudentSelect students={students} value={studentId} onChange={setStudentId} /><Select label="Status baru" value={status} onChange={(e) => setStatus(e.target.value)}>{['pindah','lulus','nonaktif','aktif'].map((s) => <option key={s} value={s}>{statusName[s]}</option>)}</Select><Textarea label="Keterangan / tujuan mutasi" value={note} onChange={(e) => setNote(e.target.value)} /><Button type="submit" disabled={saving}><Save className="h-4 w-4" />Simpan perubahan</Button></form> : <p className="text-sm text-[var(--color-ink-soft)]">Akun ini hanya dapat melihat status pada cakupannya.</p>}</SectionCard><SectionCard title="Kenaikan kelas massal" description="Akhiri rombel lama dan buat penempatan baru untuk seluruh siswa aktif.">{canManage ? <form onSubmit={promote} className="grid gap-4"><ClassSelect label="Kelas asal" classes={classes} value={fromClass} onChange={setFromClass} /><ClassSelect label="Kelas tujuan" classes={classes} value={toClass} onChange={setToClass} /><Button type="submit" disabled={saving || !fromClass || !toClass}>Naikkan siswa</Button></form> : <p className="text-sm text-[var(--color-ink-soft)]">Hanya pimpinan unit dapat melakukan kenaikan kelas massal.</p>}</SectionCard></div></div>
}

export function StudentEventsPage() {
  const { profile, canManage, loading, error, setError, students } = useStudentScope(); const [events, setEvents] = useState([]); const [form, setForm] = useState({ student_id: '', category: 'pelanggaran', title: '', description: '', points: '0', event_date: today, follow_up: '' }); const [saving, setSaving] = useState(false)
  const loadEvents = useCallback(async () => { const { data, error: eventError } = await supabase.from('student_events').select('id,category,title,description,points,event_date,follow_up,students(full_name,nis)').order('event_date', { ascending: false }).limit(80); setEvents(data || []); if (eventError) setError(eventError.message) }, [setError]); useEffect(() => { if (!loading) loadEvents() }, [loading, loadEvents])
  const save = async (e) => { e.preventDefault(); setSaving(true); const { error: saveError } = await supabase.from('student_events').insert({ ...form, points: Number(form.points || 0), created_by: profile.id }); setSaving(false); if (saveError) setError(saveError.message); else { setForm({ student_id: '', category: 'pelanggaran', title: '', description: '', points: '0', event_date: today, follow_up: '' }); loadEvents() } }
  if (loading) return <FullPageSpinner />
  return <div><PageHeader title="Kedisiplinan, BK & prestasi" description="Satu riwayat pembinaan dan pencapaian siswa yang dapat ditindaklanjuti." />{error && <p className="mb-4 text-sm text-[var(--color-danger)]">{error}</p>}<div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><SectionCard title="Catat peristiwa" description="Pelanggaran dapat menggunakan poin negatif; prestasi menggunakan poin positif.">{canManage ? <form onSubmit={save} className="grid gap-3"><StudentSelect students={students} value={form.student_id} onChange={(v) => setForm({ ...form, student_id: v })} /><Select label="Kategori" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{['pelanggaran','pembinaan_bk','prestasi'].map((v) => <option key={v} value={v}>{statusName[v]}</option>)}</Select><Input label="Judul" required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><div className="grid grid-cols-2 gap-3"><Input label="Tanggal" type="date" value={form.event_date} onChange={(e) => setForm({ ...form, event_date: e.target.value })} /><Input label="Poin" type="number" value={form.points} onChange={(e) => setForm({ ...form, points: e.target.value })} /></div><Textarea label="Keterangan" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><Textarea label="Tindak lanjut" value={form.follow_up} onChange={(e) => setForm({ ...form, follow_up: e.target.value })} /><Button type="submit" disabled={saving}>Simpan catatan</Button></form> : <p className="text-sm text-[var(--color-ink-soft)]">Pimpinan unit mengelola catatan; akses lain hanya baca.</p>}</SectionCard><SectionCard title="Riwayat peristiwa" description={`${events.length} catatan pada cakupan Anda`}><Table columns={['Tanggal','Siswa','Kategori','Catatan','Poin']}>{events.map((event) => <Tr key={event.id}><Td>{event.event_date}</Td><Td><p className="font-medium">{event.students?.full_name}</p><p className="text-xs text-[var(--color-ink-soft)]">{event.students?.nis}</p></Td><Td><Badge color={tone(event.category)}>{statusName[event.category]}</Badge></Td><Td><p>{event.title}</p>{event.follow_up && <p className="mt-1 text-xs text-[var(--color-ink-soft)]">Tindak lanjut: {event.follow_up}</p>}</Td><Td>{event.points}</Td></Tr>)}</Table></SectionCard></div></div>
}

export function GuardianCommunicationPage() {
  const { profile, canManage, loading, error, setError, students } = useStudentScope(); const [logs, setLogs] = useState([]); const [form, setForm] = useState({ student_id: '', channel: 'whatsapp', subject: '', body: '' }); const [saving, setSaving] = useState(false)
  const selected = students.find((student) => student.id === form.student_id); const guardian = selected?.guardians?.find((item) => item.is_primary_contact) || selected?.guardians?.[0]
  const loadLogs = useCallback(async () => { const { data, error: logError } = await supabase.from('guardian_outbox').select('id,channel,subject,status,created_at,students(full_name),guardians(full_name,phone,email)').order('created_at', { ascending: false }).limit(50); setLogs(data || []); if (logError) setError(logError.message) }, [setError]); useEffect(() => { if (!loading) loadLogs() }, [loading, loadLogs])
  const save = async (e) => { e.preventDefault(); if (!guardian) { setError('Siswa yang dipilih belum memiliki kontak wali.'); return } setSaving(true); const { error: saveError } = await supabase.from('guardian_outbox').insert({ student_id: selected.id, guardian_id: guardian.id, channel: form.channel, subject: form.subject, body: form.body, status: 'siap_dikirim', created_by: profile.id }); setSaving(false); if (saveError) setError(saveError.message); else { setForm({ student_id: '', channel: 'whatsapp', subject: '', body: '' }); loadLogs() } }
  const markSent = async (id) => { const { error: updateError } = await supabase.from('guardian_outbox').update({ status: 'terkirim', sent_at: new Date().toISOString() }).eq('id', id); if (updateError) setError(updateError.message); else loadLogs() }
  if (loading) return <FullPageSpinner />
  return <div><PageHeader title="Komunikasi wali" description="Siapkan dan arsipkan pesan untuk wali tanpa mengirim nomor pribadi ke luar sistem." />{error && <p className="mb-4 text-sm text-[var(--color-danger)]">{error}</p>}<div className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><SectionCard title="Pesan untuk wali" description="Status “siap dikirim” menjadi daftar kerja operator WhatsApp/email.">{canManage ? <form onSubmit={save} className="grid gap-3"><StudentSelect students={students} value={form.student_id} onChange={(v) => setForm({ ...form, student_id: v })} />{selected && <p className="rounded-xl bg-[var(--color-navy-50)] px-3 py-2 text-xs text-[var(--color-ink-soft)]">Penerima: {guardian ? `${guardian.full_name} · ${guardian.phone || guardian.email || 'kontak belum tersedia'}` : 'wali belum tersedia'}</p>}<Select label="Kanal" value={form.channel} onChange={(e) => setForm({ ...form, channel: e.target.value })}>{['whatsapp','email','in_app'].map((v) => <option key={v} value={v}>{v === 'in_app' ? 'Dalam aplikasi' : v.toUpperCase()}</option>)}</Select><Input label="Subjek" required value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} /><Textarea label="Isi pesan" required value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} /><Button type="submit" disabled={saving}><MessageCircle className="h-4 w-4" />Simpan sebagai siap dikirim</Button></form> : <p className="text-sm text-[var(--color-ink-soft)]">Akun ini dapat melihat log komunikasi sesuai cakupannya.</p>}</SectionCard><SectionCard title="Log komunikasi" description="Pencatatan internal; pengiriman WhatsApp tetap dilakukan oleh operator yang berwenang."><Table columns={['Wali / siswa','Kanal','Subjek','Status']}>{logs.map((log) => <Tr key={log.id}><Td><p className="font-medium">{log.guardians?.full_name || 'Wali'}</p><p className="text-xs text-[var(--color-ink-soft)]">{log.students?.full_name}</p></Td><Td>{log.channel}</Td><Td>{log.subject}</Td><Td>{log.status === 'siap_dikirim' && canManage ? <Button size="sm" variant="outline" onClick={() => markSent(log.id)}>Tandai terkirim</Button> : <Badge color={tone(log.status)}>{statusName[log.status]}</Badge>}</Td></Tr>)}</Table></SectionCard></div></div>
}

export function StudentInsightsPage() {
  const { loading, error, setError, students } = useStudentScope(); const [attendance, setAttendance] = useState([]); const [grades, setGrades] = useState([]); const [invoices, setInvoices] = useState([])
  useEffect(() => { if (loading) return; Promise.all([supabase.from('attendance_records').select('student_id,status,date').gte('date', `${new Date().getFullYear()}-01-01`), supabase.from('grades').select('student_id,score'), supabase.from('invoices').select('student_id,status,amount')]).then(([a, g, i]) => { setAttendance(a.data || []); setGrades(g.data || []); setInvoices(i.data || []); if (a.error || g.error || i.error) setError((a.error || g.error || i.error).message) }) }, [loading, setError])
  const report = useMemo(() => students.map((student) => { const notes = attendance.filter((item) => item.student_id === student.id); const scores = grades.filter((item) => item.student_id === student.id).map((item) => Number(item.score)); const bills = invoices.filter((item) => item.student_id === student.id && item.status !== 'lunas'); return { ...student, alpa: notes.filter((item) => item.status === 'alpa').length, hadir: notes.filter((item) => item.status === 'hadir').length, average: scores.length ? scores.reduce((a, b) => a + b, 0) / scores.length : null, bills: bills.reduce((sum, item) => sum + Number(item.amount || 0), 0) } }), [students, attendance, grades, invoices])
  if (loading) return <FullPageSpinner />
  return <div><PageHeader title="Rekap & integrasi siswa" description="Gambaran Kesiswaan yang tersambung ke presensi, Akademik, dan Keuangan." />{error && <p className="mb-4 text-sm text-[var(--color-danger)]">{error}</p>}<div className="mb-6 grid gap-4 md:grid-cols-3"><StatCard label="Siswa aktif" value={students.filter((s) => s.status === 'aktif').length} sub="Pada unit yang dapat diakses" /><StatCard label="Siswa dengan alpa" value={report.filter((r) => r.alpa > 0).length} sub="Berdasarkan presensi tahun berjalan" accent="gold" /><StatCard label="Tagihan terbuka" value={report.filter((r) => r.bills > 0).length} sub="Terhubung ke Keuangan" /></div><SectionCard title="Ringkasan siswa" description="Nilai rata-rata berasal dari Akademik; tagihan terbuka berasal dari Keuangan."><Table columns={['Siswa','Status','Hadir / alpa','Rata-rata nilai','Tagihan terbuka']}>{report.map((row) => <Tr key={row.id}><Td><p className="font-medium">{row.full_name}</p><p className="text-xs text-[var(--color-ink-soft)]">{row.nis}</p></Td><Td><Badge color={tone(row.status)}>{statusName[row.status]}</Badge></Td><Td>{row.hadir} / {row.alpa}</Td><Td>{row.average === null ? 'Belum ada nilai' : row.average.toFixed(1)}</Td><Td>{row.bills ? `Rp${row.bills.toLocaleString('id-ID')}` : 'Lunas / belum ada tagihan'}</Td></Tr>)}</Table></SectionCard></div>
}

function StudentSelect({ students, value, onChange }) { return <Select label="Siswa" required value={value} onChange={(event) => onChange(event.target.value)}><option value="">Pilih siswa</option>{students.map((student) => <option key={student.id} value={student.id}>{student.full_name} · {student.nis}</option>)}</Select> }
function ClassSelect({ label, classes, value, onChange }) { return <Select label={label} required value={value} onChange={(event) => onChange(event.target.value)}><option value="">Pilih kelas</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select> }
