import { useCallback, useEffect, useState } from 'react'
import { Plus, Save } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
import { useAuth } from '../../context/AuthContext'
import { PageHeader, SectionCard, Button, Input, Select, Textarea, Table, Tr, Td, Badge, FullPageSpinner } from '../../components/ui'

const leadership = ['admin_yayasan', 'admin_unit', 'kepala_sekolah', 'wakil_kepala_sekolah']
const today = new Date().toISOString().slice(0, 10)
const labelStatus = (value) => ({ aktif: 'Aktif', lulus: 'Lulus', pindah: 'Pindah', nonaktif: 'Nonaktif', hadir: 'Hadir', sakit: 'Sakit', izin: 'Izin', alpa: 'Alpa', diajukan: 'Diajukan', disetujui: 'Disetujui', ditolak: 'Ditolak', dispensasi: 'Dispensasi' }[value] || value)
const badge = (value) => (['aktif', 'hadir', 'disetujui'].includes(value) ? 'success' : ['alpa', 'ditolak', 'nonaktif'].includes(value) ? 'danger' : 'gold')

function useSchoolData() {
  const { profile } = useAuth(); const canManage = leadership.includes(profile?.role)
  const [students, setStudents] = useState([]); const [classes, setClasses] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); const [{ data: s, error: se }, { data: c }] = await Promise.all([supabase.from('students').select('id,nis,full_name,current_unit_id,status,guardians(id,full_name,phone,email,relation,is_primary_contact)').order('full_name'), supabase.from('classes').select('id,name,unit_id').order('name')]); setStudents(s || []); setClasses(c || []); setError(se?.message || ''); setLoading(false) }, [])
  useEffect(() => { load() }, [load]); return { profile, canManage, students, classes, loading, error, setError, load }
}

export function StudentProfilesPage() {
  const { canManage, students, loading, error, setError, load } = useSchoolData(); const [selectedId, setSelectedId] = useState(''); const [saving, setSaving] = useState(false)
  const selected = students.find((s) => s.id === selectedId) || students[0]; const guardian = selected?.guardians?.find((g) => g.is_primary_contact) || selected?.guardians?.[0]
  const [form, setForm] = useState({ full_name: '', nis: '', status: 'aktif', guardian_name: '', guardian_phone: '', guardian_email: '' })
  useEffect(() => { if (selected) setForm({ full_name: selected.full_name || '', nis: selected.nis || '', status: selected.status || 'aktif', guardian_name: guardian?.full_name || '', guardian_phone: guardian?.phone || '', guardian_email: guardian?.email || '' }) }, [selectedId, selected?.id])
  const save = async (e) => { e.preventDefault(); if (!selected || !canManage) return; setSaving(true); setError(''); const { error: studentError } = await supabase.from('students').update({ full_name: form.full_name.trim(), nis: form.nis.trim(), status: form.status }).eq('id', selected.id); if (studentError) { setError(studentError.message); setSaving(false); return }; const payload = { student_id: selected.id, full_name: form.guardian_name.trim() || 'Belum diisi', phone: form.guardian_phone.trim() || null, email: form.guardian_email.trim() || null, relation: 'Orang tua/wali', is_primary_contact: true }; const { error: guardianError } = guardian ? await supabase.from('guardians').update(payload).eq('id', guardian.id) : await supabase.from('guardians').insert(payload); if (guardianError) setError(guardianError.message); setSaving(false); load() }
  if (loading) return <FullPageSpinner />
  return <div><PageHeader title="Profil siswa & wali" description="Perbarui data induk dan kontak utama orang tua/wali." />{error && <p className="mb-4 text-sm text-[var(--color-danger)]">{error}</p>}<div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><SectionCard title="Pilih siswa" description={`${students.length} siswa pada cakupan akun`}><div className="max-h-[520px] overflow-y-auto">{students.map((s) => <button key={s.id} onClick={() => setSelectedId(s.id)} className={`w-full border-b px-1 py-3 text-left last:border-0 ${selected?.id === s.id ? 'text-[var(--color-navy)]' : ''}`}><p className="font-medium">{s.full_name}</p><p className="text-xs text-[var(--color-ink-soft)]">{s.nis} · {labelStatus(s.status)}</p></button>)}</div></SectionCard><SectionCard title={selected ? selected.full_name : 'Belum ada siswa'} description={canManage ? 'Perubahan tersimpan pada data operasional.' : 'Akun Anda hanya dapat melihat data.'}>{selected ? <form onSubmit={save} className="grid gap-4"><div className="grid gap-4 sm:grid-cols-2"><Input label="Nama lengkap" value={form.full_name} disabled={!canManage} onChange={(e) => setForm({...form,full_name:e.target.value})} /><Input label="NIS" value={form.nis} disabled={!canManage} onChange={(e) => setForm({...form,nis:e.target.value})} /><Select label="Status siswa" value={form.status} disabled={!canManage} onChange={(e) => setForm({...form,status:e.target.value})}>{['aktif','pindah','lulus','nonaktif'].map((v)=><option key={v} value={v}>{labelStatus(v)}</option>)}</Select></div><div className="border-t pt-4"><p className="mb-3 font-medium">Kontak utama wali</p><div className="grid gap-4 sm:grid-cols-2"><Input label="Nama wali" value={form.guardian_name} disabled={!canManage} onChange={(e) => setForm({...form,guardian_name:e.target.value})}/><Input label="Telepon / WhatsApp" value={form.guardian_phone} disabled={!canManage} onChange={(e) => setForm({...form,guardian_phone:e.target.value})}/><Input label="Email wali" type="email" value={form.guardian_email} disabled={!canManage} onChange={(e) => setForm({...form,guardian_email:e.target.value})}/></div></div>{canManage && <div className="flex justify-end"><Button type="submit" disabled={saving}><Save className="h-4 w-4" />{saving ? 'Menyimpan…' : 'Simpan profil'}</Button></div>}</form> : <p className="text-sm text-[var(--color-ink-soft)]">Tambahkan siswa terlebih dahulu.</p>}</SectionCard></div></div>
}

export function StudentPlacementPage() {
  const { canManage, students, classes, loading, error, setError, load } = useSchoolData(); const [records, setRecords] = useState([]); const [form, setForm] = useState({ student_id: '', class_id: '' }); const [saving,setSaving]=useState(false)
  const loadRecords = useCallback(async () => { const { data, error: e } = await supabase.from('class_enrollments').select('id,enrolled_at,ended_at,students(full_name,nis),classes(name)').order('enrolled_at',{ascending:false}); setRecords(data||[]); if(e)setError(e.message) }, [setError])
  useEffect(()=>{ if(!loading)loadRecords() },[loading,loadRecords])
  const assign = async (e) => { e.preventDefault(); setSaving(true); const { error:e2 }=await supabase.from('class_enrollments').insert({student_id:form.student_id,class_id:form.class_id}); setSaving(false); if(e2)setError(e2.message); else {setForm({student_id:'',class_id:''}); loadRecords(); load()} }
  const finish = async (id) => { const {error:e}=await supabase.from('class_enrollments').update({ended_at:new Date().toISOString()}).eq('id',id); if(e)setError(e.message); else loadRecords() }
  if(loading)return <FullPageSpinner />
  return <div><PageHeader title="Penempatan & riwayat kelas" description="Tempatkan siswa ke rombel dan simpan jejak perpindahan kelas." />{error&&<p className="mb-4 text-sm text-[var(--color-danger)]">{error}</p>}<div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><SectionCard title="Penempatan baru" description={canManage?'Pilih siswa dan kelas sesuai unit.':'Hanya pimpinan unit yang dapat mengubah penempatan.'}>{canManage&&<form onSubmit={assign} className="grid gap-4"><Select label="Siswa" required value={form.student_id} onChange={(e)=>setForm({...form,student_id:e.target.value})}><option value="">Pilih siswa</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name} · {s.nis}</option>)}</Select><Select label="Kelas / rombel" required value={form.class_id} onChange={(e)=>setForm({...form,class_id:e.target.value})}><option value="">Pilih kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Button type="submit" disabled={saving}><Plus className="h-4 w-4" />{saving?'Menyimpan…':'Tempatkan siswa'}</Button></form>}</SectionCard><SectionCard title="Riwayat penempatan" description={`${records.length} catatan`}><Table columns={['Siswa','Kelas','Mulai','Status']}>{records.map(r=><Tr key={r.id}><Td><p className="font-medium">{r.students?.full_name}</p><p className="text-xs text-[var(--color-ink-soft)]">{r.students?.nis}</p></Td><Td>{r.classes?.name}</Td><Td>{r.enrolled_at ? new Date(r.enrolled_at).toLocaleDateString('id-ID') : '—'}</Td><Td>{r.ended_at?<Badge color="neutral">Selesai</Badge>:canManage?<Button size="sm" variant="outline" onClick={()=>finish(r.id)}>Akhiri</Button>:<Badge color="success">Aktif</Badge>}</Td></Tr>)}</Table></SectionCard></div></div>
}

export function StudentAttendancePermissionPage() {
  const { profile, canManage, students, classes, loading, error, setError } = useSchoolData(); const [attendance,setAttendance]=useState([]); const [permissions,setPermissions]=useState([]); const [a,setA]=useState({student_id:'',class_id:'',status:'hadir',date:today,note:''}); const [p,setP]=useState({student_id:'',class_id:'',permission_type:'izin',start_date:today,end_date:today,reason:''})
  const load = useCallback(async()=>{const[{data:ad,error:ae},{data:pd,error:pe}]=await Promise.all([supabase.from('attendance_records').select('id,date,status,note,students(full_name),classes(name)').order('date',{ascending:false}).limit(30),supabase.from('student_permissions').select('id,permission_type,start_date,end_date,reason,status,students(full_name)').order('created_at',{ascending:false}).limit(30)]);setAttendance(ad||[]);setPermissions(pd||[]);if(ae||pe)setError((ae||pe).message)},[setError]);useEffect(()=>{if(!loading)load()},[loading,load])
  const submitAttendance=async(e)=>{e.preventDefault();const{error:e2}=await supabase.from('attendance_records').insert({...a,recorded_by:profile.id});if(e2)setError(e2.message);else{setA({...a,note:''});load()}}; const submitPermission=async(e)=>{e.preventDefault();const{error:e2}=await supabase.from('student_permissions').insert({...p,requested_by:profile.id});if(e2)setError(e2.message);else{setP({...p,reason:''});load()}}; const reviewPermission=async(id,status)=>{const{error:e2}=await supabase.from('student_permissions').update({status,reviewed_by:profile.id,reviewed_at:new Date().toISOString()}).eq('id',id);if(e2)setError(e2.message);else load()}
  if(loading)return <FullPageSpinner />
  return <div><PageHeader title="Presensi & izin siswa" description="Catat kehadiran harian dan kelola permohonan izin." />{error&&<p className="mb-4 text-sm text-[var(--color-danger)]">{error}</p>}<div className="grid gap-6 lg:grid-cols-2"><SectionCard title="Catat presensi" description="Untuk kelas yang menjadi kewenangan Anda."><form onSubmit={submitAttendance} className="grid gap-3"><StudentClassFields students={students} classes={classes} form={a} setForm={setA}/><Select label="Status" value={a.status} onChange={e=>setA({...a,status:e.target.value})}>{['hadir','sakit','izin','alpa'].map(v=><option key={v} value={v}>{labelStatus(v)}</option>)}</Select><Input label="Tanggal" type="date" value={a.date} onChange={e=>setA({...a,date:e.target.value})}/><Textarea label="Catatan" value={a.note} onChange={e=>setA({...a,note:e.target.value})}/><Button type="submit">Simpan presensi</Button></form></SectionCard><SectionCard title="Ajukan izin" description={canManage?'Pengajuan dicatat untuk ditinjau.':'Data izin dapat dibaca sesuai siswa yang diakses.'}>{canManage&&<form onSubmit={submitPermission} className="grid gap-3"><StudentClassFields students={students} classes={classes} form={p} setForm={setP}/><Select label="Jenis" value={p.permission_type} onChange={e=>setP({...p,permission_type:e.target.value})}>{['izin','sakit','dispensasi'].map(v=><option key={v} value={v}>{labelStatus(v)}</option>)}</Select><div className="grid grid-cols-2 gap-3"><Input label="Mulai" type="date" value={p.start_date} onChange={e=>setP({...p,start_date:e.target.value})}/><Input label="Selesai" type="date" value={p.end_date} onChange={e=>setP({...p,end_date:e.target.value})}/></div><Textarea label="Alasan" value={p.reason} onChange={e=>setP({...p,reason:e.target.value})}/><Button type="submit">Ajukan izin</Button></form>}</SectionCard></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><SectionCard title="Presensi terbaru"><Table columns={['Tanggal','Siswa','Status']}>{attendance.map(r=><Tr key={r.id}><Td>{r.date}</Td><Td>{r.students?.full_name}</Td><Td><Badge color={badge(r.status)}>{labelStatus(r.status)}</Badge></Td></Tr>)}</Table></SectionCard><SectionCard title="Izin terbaru"><Table columns={['Siswa','Jenis / periode','Status']}>{permissions.map(r=><Tr key={r.id}><Td>{r.students?.full_name}</Td><Td>{labelStatus(r.permission_type)} · {r.start_date} s/d {r.end_date}</Td><Td>{canManage&&r.status==='diajukan'?<span className="flex gap-2"><Button size="sm" onClick={()=>reviewPermission(r.id,'disetujui')}>Setujui</Button><Button size="sm" variant="outline" onClick={()=>reviewPermission(r.id,'ditolak')}>Tolak</Button></span>:<Badge color={badge(r.status)}>{labelStatus(r.status)}</Badge>}</Td></Tr>)}</Table></SectionCard></div></div>
}
function StudentClassFields({students,classes,form,setForm}){return <><Select label="Siswa" required value={form.student_id} onChange={e=>setForm({...form,student_id:e.target.value})}><option value="">Pilih siswa</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name} · {s.nis}</option>)}</Select><Select label="Kelas" required value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})}><option value="">Pilih kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></>}
