import { useCallback, useEffect, useState } from 'react'
import { Building2, ShieldCheck, Database, Plus } from 'lucide-react'
import { supabase } from '../../lib/supabaseClient'
import { PageHeader, Card, SectionCard, Button, Input, EmptyState, FullPageSpinner } from '../../components/ui'
export default function YayasanAdmin() {
  const [units, setUnits] = useState([]); const [counts, setCounts] = useState({ profiles: 0, students: 0 }); const [form, setForm] = useState({ code: '', name: '' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); const [{ data: u }, { count: profiles }, { count: students }] = await Promise.all([supabase.from('units').select('id, code, name').order('code'), supabase.from('profiles').select('id', { count: 'exact', head: true }), supabase.from('students').select('id', { count: 'exact', head: true })]); setUnits(u || []); setCounts({ profiles: profiles || 0, students: students || 0 }); setLoading(false) }, [])
  useEffect(() => { load() }, [load])
  const addUnit = async (e) => { e.preventDefault(); setSaving(true); setError(''); const { error: err } = await supabase.from('units').insert({ code: form.code.trim().toUpperCase(), name: form.name.trim() }); setSaving(false); if (err) { setError(err.message); return }; setForm({ code: '', name: '' }); load() }
  if (loading) return <FullPageSpinner />
  return <div><PageHeader title="Admin Yayasan" description="Pusat pengaturan project Supabase GPT untuk seluruh unit Darussunah." /><div className="grid gap-4 sm:grid-cols-3 mb-6"><Stat icon={Building2} label="Unit sekolah" value={units.length} /><Stat icon={ShieldCheck} label="Akun pengguna" value={counts.profiles} /><Stat icon={Database} label="Data siswa" value={counts.students} /></div><div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><SectionCard title="Unit Yayasan" description="SD, SMP, SMA, atau unit lain yang dikelola yayasan.">{units.length === 0 ? <EmptyState icon={Building2} title="Belum ada unit" description="Tambahkan unit pertama di panel sebelah." /> : <div className="divide-y">{units.map((u) => <div key={u.id} className="flex items-center justify-between py-3"><div><p className="font-semibold">{u.name}</p><p className="text-xs text-[var(--color-ink-soft)]">Kode {u.code}</p></div><span className="rounded-full bg-[var(--color-navy-50)] px-2.5 py-1 text-xs font-semibold text-[var(--color-navy)]">Aktif</span></div>)}</div>}</SectionCard><Card><h2 className="text-lg font-semibold">Tambah unit</h2><p className="mt-1 text-sm text-[var(--color-ink-soft)]">Data tersimpan langsung di project GPT.</p><form onSubmit={addUnit} className="mt-5 flex flex-col gap-4"><Input label="Kode unit" placeholder="SD" required value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /><Input label="Nama unit" placeholder="SD Darussunah" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />{error && <p className="text-sm text-[var(--color-danger)]">{error}</p>}<Button type="submit" disabled={saving}><Plus className="h-4 w-4" />{saving ? 'Menyimpan…' : 'Simpan unit'}</Button></form></Card></div></div>
}
function Stat({ icon: Icon, label, value }) { return <Card><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[var(--color-navy-50)] text-[var(--color-navy)]"><Icon className="h-5 w-5" /></div><div><p className="text-sm text-[var(--color-ink-soft)]">{label}</p><p className="text-2xl font-semibold">{value}</p></div></div></Card> }

